base: ../base.yaml

output_dir: ${output_dir}/clinc150_ruler_64k
run_name: clinc150_ruler_64k

training:
  max_length: 65536

data:
  datasets:
    - ${data_dir}/ruler_mk_uuid_64k/development.jsonl
    - ${data_dir}/clinc150_64k/development.jsonl
