base: ../base.yaml

output_dir: ${output_dir}/infinite_bench_mc_64k
run_name: infinite_bench_mc_64k

training:
  max_length: 65536

data:
  datasets:
    - ${data_dir}/infinite_bench_mc_64k/development.jsonl
