base: ../base.yaml

output_dir: ${output_dir}/nlu_msmacro_64k
run_name: nlu_msmacro_64k

training:
  max_length: 65536

data:
  datasets:
    - ${data_dir}/ms_macro_64k/development.jsonl
    - ${data_dir}/nlu_64k/development.jsonl
