base: ../base.yaml

output_dir: ${output_dir}/clinc150_ruler_128k
run_name: clinc150_ruler_128k

training:
  max_length: 131072

data:
  datasets:
    - ${data_dir}/ruler_mk_uuid_128k/development.jsonl
    - ${data_dir}/clinc150_128k/development.jsonl
