base: ../base.yaml

output_dir: ${output_dir}/nlu_msmacro_128k
run_name: nlu_msmacro_128k

training:
  max_length: 131072

data:
  datasets:
    - ${data_dir}/ms_macro_128k/development.jsonl
    - ${data_dir}/nlu_128k/development.jsonl
