base: ../base.yaml

output_dir: ${output_dir}/ruler_mk_uuid_128k
run_name: ruler_mk_uuid_128k

training:
  max_length: 131072

data:
  datasets:
    - ${data_dir}/ruler_mk_uuid_128k/development.jsonl
