base: ../base.yaml

output_dir: ${output_dir}/trec_infbenchmc_128k
run_name: trec_infbenchmc_128k

training:
  max_length: 131072

data:
  datasets:
    - ${data_dir}/infinite_bench_mc_128k/development.jsonl
    - ${data_dir}/trec_coarse_128k/development.jsonl
